var tableauQuestion = [
    {   question : "Scenario: My friend is being arrested by police for minor offences, I'm going to run down police what is the correct answer?:",
        propositionA : "This would be fail role-play, I wouldn't do this.",
        propositionB : "This would be fair and reasonable to do.",
        propositionC : "The cops need to learn a thing or two.",
        propositionD : "Where am I again?",
        reponse : "A",
		reponseb : "A"},
    {   question : "Scenario: A member of an outlaw motor cycle gang is walking to get his car, me and my mate taunt them:",
        propositionA : "This is ok and reasonable role-play as there are more of us than them.",
        propositionB : "Its a bad idea, as with most gangs/OMCG's you pick on one, you pick on them all - I may never walk again.",
        propositionC : "This could be fail role-play as in most cirumstances you wouldn't dare do this IRL.",
        propositionD : "I would beat them up and all his friends as well.",
        reponse : "B",
		reponseb : "C"},
    {   question : "If you break the rules, what can you expect?",
        propositionA : "To be given a yellow card or red card and possibly be removed from Role-play if my behaviour is bad enough.",
        propositionB : "To be given a soft drink.",
        propositionC : "To be given a ice cream.",
        propositionD : "To be given a cash prize.",
        reponse : "A",
		reponseb : "A"},
	{   question : "Where can I find the rules for BlueBirdRP?",
        propositionA : "In the F3 menu and also on www.bluebirdrp.live website.",
        propositionB : "Check your blind spots.",
        propositionC : "Signal your intentions.",
        propositionD : "Not sure.",
        reponse : "A",
		reponseb : "A"
	},
	{   question : "When you role-play you...  (choose the best answer)",
        propositionA : "Assume a character and do whatever the hell you want. Thats the point?",
        propositionB : "Assume a character, setup an identity. Act out that character within the rules of the city and be fair with other role-players.",
        propositionC : "Take over the role-play, because I'm the biggest star in my own show.",
        propositionD : "Interrupt other peoples role-play (people need to learn to share and deal with it yo).",
        reponse : "B",
		reponseb : "B"
	},
	{   question : "When you do hostile role-play:",
		propositionA : "You need to have at least <strong>4</strong> cops on. But I should always be mindful of police numbers.",
        propositionB : "You should always carry a piece of apple pie",
        propositionC : "You should use your indicator first before turning on hostile roleplay.",
        propositionD : "You should always wear underwear.",
        reponse : "A",
		reponseb : "A"
	},
	{   question : "What is the best role-play outcome?",
		propositionA : "I get to win everything and to hell with everyone else.",
        propositionB : "People get trolled and its just amazing fun.",
        propositionC : "RDM and VDM for the win hell yes!",
        propositionD : "Where everyone has a good time, has fun, is treated fairly and equally",
        reponse : "A",
		reponseb : "A"
	},
	{   question : "What should I do if I see someone breaking the rules?",
		propositionA : "Start abusing the moron in Out of Character Chat",
        propositionB : "Hurling verbal abuse at the 'son of a gun'.",
        propositionC : "Use /report to inform moderators and admins while still engaging and finishing the role-play for the benefit of others around.",
        propositionD : "Combat log",
        reponse : "C",
		reponseb : "C"
	},
	{   question : "Where I find an exploit in the city that gives me an advantage that wouldn't or shouldn't normally be available I will (choose the best answer):",
		propositionA : "Take full advantage of it as they shouldn't have made it that way.",
        propositionB : "Report it to an admin so that they are aware and can get it fixed.",
        propositionC : "Raise a ticket on the forums so that it can be fixed.",
        propositionD : "Keep it to myself. It'll be worth something later on.",
        reponse : "B",
		reponseb : "C"
	},
	{   question : "If I don't lock my car when I am in the city:",
		propositionA : "It and all its contents can be stolen only when there are <strong>4</strong> or more cops on?",
        propositionB : "Elephants should be pink and not yellow.",
        propositionC : "Tigers could case cars.",
        propositionD : "People should be alive.",
        reponse : "A",
		reponseb : "A"
	},
	{   question : "Scenario: I'm bored as hell.. I want a cop chase, I drop a doughie in front of the cops or ram them. What can I expect?",
		propositionA : "A yellow card, red card or ban for role-play baiting.",
        propositionB : "A thank you from the police.",
        propositionC : "A merry christmas and happy new year from the dev team.",
        propositionD : "A hi5 and hello from the Admin team.",
        reponse : "A",
		reponseb : "A"
	},
	{   question : "Scenario: I do the same troll role-play over and over again, because I enjoy it. What can I expect?",
		propositionA : "A hi5 and hello from the Admin team.",
        propositionB : "A thank you from the police.",
        propositionC : "A merry christmas and happy new year from the dev team.",
        propositionD : "Unhappy People, no one likes Troll role-play, even criminals can think outside the square.",
        reponse : "D",
		reponseb : "D"
	},
	{   question : "Scenario: I'm driving my car at 150km/h and get into an accident, I'm still alive, the car is dead....",
		propositionA : "I jump out fix the vehicle, and take off like nothing happened.",
        propositionB : "I run from the scene at full speed to escape the cops who were chasing me. F#*&# the pigs bro.",
        propositionC : "I role-play my injuries and if concious call for help with my mobile phone.",
        propositionD : "Combat Log.",
        reponse : "C",
		reponseb : "C"
	},
	{   question : "Scenario: I'm being chased, I get cornered, they wont take me alive. I exit the game quickly so they cant catch me. What will happen?",
		propositionA : "A player will report me, the admins can see who has left the city and area of the city they left, I will receive a ban for combat logging.",
        propositionB : "I will get away and there is nothing they can do.",
        propositionC : "Its all too late anyway who cares?",
        propositionD : "I'm just here to troll.",
        reponse : "A",
		reponseb : "A"
	},
	{   question : "Scenario: I'm in a fast car, I'll drive in the city as fast as all get out. What will be the outcome?",
		propositionA : "You'll receive multiple speeding tickets by the camera ranging from $100-12k and your character won't be reset. You may receive other government intervention.",
        propositionB : "This is GTA online, if the car goes fast, I will drive it fast - end of.",
        propositionC : "It doesn't matter.",
        propositionD : "I'm just here to troll.",
        reponse : "A",
		reponseb : "A"
	},
	{   question : "Scenario: I like erotic role-play and I like to talk about my big d!c* and I'll be very inappropriate. What will be the outcome?",
		propositionA : "Sunshine lollipops and rainbows.",
        propositionB : "I will be permanently banned within 0.25 seconds of being inappropriate.",
        propositionC : "It doesn't matter.",
        propositionD : "I'm just here to troll.",
        reponse : "B",
		reponseb : "B"
	},	
     {   question : "Scenario: I've been shot and I'm unconscious. BlueBird has a new life rule this means:",
        propositionA : "I will go and seek revenge once I 're-spawn' - they better look out.",
        propositionB : "I want to be the colour yellow.",
        propositionC : "If I don't receive medical attention either by a paramedic I will have to forget everything that led up to the incident.",
        propositionD : "I'm just here to troll.",
        reponse : "C",
        reponseb : "C"
    },
	{   question : "I'm starting my own gang - we're going to f#!k people up:",
		propositionA : "I'm just here to troll.",
        propositionB : "No one will tell me what to do.",
        propositionC : "I'm done reading this stuff.",
        propositionD : "I need to have my gang approved and registered with the federal government before we can label ourselves and operate in the city.<br/>I also need to follow the BlueBird rules in F3.",
        reponse : "D",
		reponseb : "D"
	},	
	{   question : "Scenario: I'm role-playing in Melbourne Australia in 2020. I'm going to:",
		propositionA : "Pretend this is America and shoot up the cops with my guns or run them down with my fast car.",
        propositionB : "No one will tell me what to do, not even the admins or mods here.",
        propositionC : "Speed through the city as fast as my car allows. I might stop if I get pulled over, but probably won't.",
        propositionD : "Role-play realistically by not doing things that wouldn't occur in Australia. If I'm unsure I'll ask for advice and speak to an admin in the discord.",
        reponse : "D",
		reponseb : "D"
	},	
	{   question : "Scenario: You're only interested in criminal role-play. You go around robbing everyone all the time. What best describes this sentence?",
		propositionA : "The role-play is exciting and will be enjoyed by everyone on BlueBird.",
        propositionB : "You should consider improving parts of your role-play if you plan to stay at BlueBird for any length of time.",
        propositionC : "The role-play will struggle to be accepted all the time by members in the BlueBird community. I should consider other role-play ideas.",
        propositionD : "I will get real rich really quickly.",
        reponse : "B",
		reponseb : "C"
	},
	{   question : "Scenario: A role-play is happening in front of me, I'm not involved. But I want to be. What would be the best answer?",
		propositionA : "You shouldn't interject in someone elses role-play, as it can be disruptive and ruin a role-play.",
        propositionB : "Dive right in, they can't control what happens.",
        propositionC : "Observe if reasonable, only if you have something to positively build on the role-play should you 'nudge in' but monitor social queues and be prepared to 'nudge out'.",
        propositionD : "I will get real rich really quickly.",
        reponse : "A",
		reponseb : "C"
	},	
	{   question : "Warning: THIS SERVER IS PERMANENT BAN HAPPY: IF YOU BREAK THE RULES (THIS IS YOUR WARNING) - YOU WILL BE BANNED - If you're not interested in serious Role play press F8 and type QUIT now",
		propositionA : "I UNDERSTAND, that it takes seconds to be banned but over a month to be unbanned (theres a large amount of ban appeals)",
        propositionB : "Ban me now, I dont care I'll do what I like I'm here to troll.",
        propositionC : "I'm here to troll you, ban me, ban me.",
        propositionD : "Don't care",
        reponse : "A",
		reponseb : "A"
	},			
]
