Config = {}
Config.Locale = "en"

Config.Weapons = {
  WEAPON_KNIFE = {hash = `WEAPON_KNIFE`, item = 'weapon_knife', label = _U('weapon_knife') },
  WEAPON_NIGHTSTICK = {hash = `WEAPON_NIGHTSTICK`, item = 'weapon_nightstick', label = _U('weapon_nightstick') },
  WEAPON_HAMMER = {hash = `WEAPON_HAMMER`, item = 'weapon_hammer', label = _U('weapon_hammer') },
  WEAPON_BAT = {hash = `WEAPON_BAT`, item = 'weapon_bat', label = _U('weapon_bat') },
  WEAPON_GOLFCLUB = {hash = `WEAPON_GOLFCLUB`, item = 'weapon_golfclub', label = _U('weapon_golfclub') },
  WEAPON_CROWBAR = {hash = `WEAPON_CROWBAR`, item = 'weapon_crowbar', label = _U('weapon_crowbar') },
  WEAPON_PISTOL = {hash = `WEAPON_PISTOL`, item = 'weapon_pistol', label = _U('weapon_pistol') },
  WEAPON_COMBATPISTOL = {hash = `WEAPON_COMBATPISTOL`, item = 'weapon_combatpistol', label = _U('weapon_combatpistol') },
  WEAPON_APPISTOL = {hash = `WEAPON_APPISTOL`, item = 'weapon_appistol', label = _U('weapon_appistol') },
  WEAPON_PISTOL50 = {hash = `WEAPON_PISTOL50`, item = 'weapon_pistol50', label = _U('weapon_pistol50') },
  WEAPON_MICROSMG = {hash = `WEAPON_MICROSMG`, item = 'weapon_microsmg', label = _U('weapon_microsmg') },
  WEAPON_SMG = {hash = `WEAPON_SMG`, item = 'weapon_smg', label = _U('weapon_smg') },
  WEAPON_ASSAULTSMG = {hash = `WEAPON_ASSAULTSMG`, item = 'weapon_assaultsmg', label = _U('weapon_assaultsmg') },
  WEAPON_ASSAULTRIFLE = {hash = `WEAPON_ASSAULTRIFLE`, item = 'weapon_assaultrifle', label = _U('weapon_assaultrifle') },
  WEAPON_CARBINERIFLE = {hash = `WEAPON_CARBINERIFLE`, item = 'weapon_carbinerifle', label = _U('weapon_carbinerifle') },
  WEAPON_ADVANCEDRIFLE = {hash = `WEAPON_ADVANCEDRIFLE`, item = 'weapon_advancedrifle', label = _U('weapon_advancedrifle') },
  WEAPON_MG = {hash = `WEAPON_MG`, item = 'weapon_mg', label = _U('weapon_mg') },
  WEAPON_COMBATMG = {hash = `WEAPON_COMBATMG`, item = 'weapon_combatmg', label = _U('weapon_combatmg') },
  WEAPON_PUMPSHOTGUN = {hash = `WEAPON_PUMPSHOTGUN`, item = 'weapon_pumpshotgun', label = _U('weapon_pumpshotgun') },
  WEAPON_SAWNOFFSHOTGUN = {hash = `WEAPON_SAWNOFFSHOTGUN`, item = 'weapon_sawnoffshotgun', label = _U('weapon_sawnoffshotgun') },
  WEAPON_ASSAULTSHOTGUN = {hash = `WEAPON_ASSAULTSHOTGUN`, item = 'weapon_assaultshotgun', label = _U('weapon_assaultshotgun') },
  WEAPON_BULLPUPSHOTGUN = {hash = `WEAPON_BULLPUPSHOTGUN`, item = 'weapon_bullpupshotgun', label = _U('weapon_bullpupshotgun') },
  WEAPON_STUNGUN = {hash = `WEAPON_STUNGUN`, item = 'weapon_stungun', label = _U('weapon_stungun') },
  WEAPON_SNIPERRIFLE = {hash = `WEAPON_SNIPERRIFLE`, item = 'weapon_sniperrifle', label = _U('weapon_sniperrifle') },
  WEAPON_HEAVYSNIPER = {hash = `WEAPON_HEAVYSNIPER`, item = 'weapon_heavysniper', label = _U('weapon_heavysniper') },
  WEAPON_REMOTESNIPER = {hash = `WEAPON_REMOTESNIPER`, item = 'weapon_remotesniper', label = _U('weapon_remotesniper') },
  WEAPON_GRENADELAUNCHER = {hash = `WEAPON_GRENADELAUNCHER`, item = 'weapon_grenadelauncher', label = _U('weapon_grenadelauncher') },
  WEAPON_RPG = {hash = `WEAPON_RPG`, item = 'weapon_rpg', label = _U('weapon_rpg') },
  WEAPON_STINGER = {hash = `WEAPON_STINGER`, item = 'weapon_stinger', label = _U('weapon_stinger') },
  WEAPON_MINIGUN = {hash = `WEAPON_MINIGUN`, item = 'weapon_minigun', label = _U('weapon_minigun') },
  WEAPON_GRENADE = {hash = `WEAPON_GRENADE`, item = 'weapon_grenade', label = _U('weapon_grenade') },
  WEAPON_STICKYBOMB = {hash = `WEAPON_STICKYBOMB`, item = 'weapon_stickybomb', label = _U('weapon_stickybomb') },
  WEAPON_SMOKEGRENADE = {hash = `WEAPON_SMOKEGRENADE`, item = 'weapon_smokegrenade', label = _U('weapon_smokegrenade') },
  WEAPON_BZGAS = {hash = `WEAPON_BZGAS`, item = 'weapon_bzgas', label = _U('weapon_bzgas') },
  WEAPON_MOLOTOV = {hash = `WEAPON_MOLOTOV`, item = 'weapon_molotov', label = _U('weapon_molotov') },
  WEAPON_FIREEXTINGUISHER = {hash = `WEAPON_FIREEXTINGUISHER`, item = 'weapon_fireextinguisher', label = _U('weapon_fireextinguisher') },
  WEAPON_PETROLCAN = {hash = `WEAPON_PETROLCAN`, item = 'weapon_petrolcan', label = _U('weapon_petrolcan') },
  WEAPON_DIGISCANNER = {hash = `WEAPON_DIGISCANNER`, item = 'weapon_digiscanner', label = _U('weapon_digiscanner') },
  WEAPON_BALL = {hash = `WEAPON_BALL`, item = 'weapon_ball', label = _U('weapon_ball') },
  WEAPON_SNSPISTOL = {hash = `WEAPON_SNSPISTOL`, item = 'weapon_snspistol', label = _U('weapon_snspistol') },
  WEAPON_BOTTLE = {hash = `WEAPON_BOTTLE`, item = 'weapon_bottle', label = _U('weapon_bottle') },
  WEAPON_GUSENBERG = {hash = `WEAPON_GUSENBERG`, item = 'weapon_gusenberg', label = _U('weapon_gusenberg') },
  WEAPON_SPECIALCARBINE = {hash = `WEAPON_SPECIALCARBINE`, item = 'weapon_specialcarbine', label = _U('weapon_specialcarbine') },
  WEAPON_HEAVYPISTOL = {hash = `WEAPON_HEAVYPISTOL`, item = 'weapon_heavypistol', label = _U('weapon_heavypistol') },
  WEAPON_BULLPUPRIFLE = {hash = `WEAPON_BULLPUPRIFLE`, item = 'weapon_bullpuprifle', label = _U('weapon_bullpuprifle') },
  WEAPON_DAGGER = {hash = `WEAPON_DAGGER`, item = 'weapon_dagger', label = _U('weapon_dagger') },
  WEAPON_VINTAGEPISTOL = {hash = `WEAPON_VINTAGEPISTOL`, item = 'weapon_vintagepistol', label = _U('weapon_vintagepistol') },
  WEAPON_FIREWORK = {hash = `WEAPON_FIREWORK`, item = 'weapon_firework', label = _U('weapon_firework') },
  WEAPON_MUSKET = {hash = `WEAPON_MUSKET`, item = 'weapon_musket', label = _U('weapon_musket') },
  WEAPON_HEAVYSHOTGUN = {hash = `WEAPON_HEAVYSHOTGUN`, item = 'weapon_heavyshotgun', label = _U('weapon_heavyshotgun') },
  WEAPON_MARKSMANRIFLE = {hash = `WEAPON_MARKSMANRIFLE`, item = 'weapon_marksmanrifle', label = _U('weapon_marksmanrifle') },
  WEAPON_HOMINGLAUNCHER = {hash = `WEAPON_HOMINGLAUNCHER`, item = 'weapon_hominglauncher', label = _U('weapon_hominglauncher') },
  WEAPON_PROXMINE = {hash = `WEAPON_PROXMINE`, item = 'weapon_proxmine', label = _U('weapon_proxmine') },
  WEAPON_SNOWBALL = {hash = `WEAPON_SNOWBALL`, item = 'weapon_snowball', label = _U('weapon_snowball') },
  WEAPON_FLAREGUN = {hash = `WEAPON_FLAREGUN`, item = 'weapon_flaregun', label = _U('weapon_flaregun') },
  WEAPON_GARBAGEBAG = {hash = `WEAPON_GARBAGEBAG`, item = 'weapon_garbagebag', label = _U('weapon_garbagebag') },
  WEAPON_HANDCUFFS = {hash = `WEAPON_HANDCUFFS`, item = 'weapon_handcuffs', label = _U('weapon_handcuffs') },
  WEAPON_COMBATPDW = {hash = `WEAPON_COMBATPDW`, item = 'weapon_combatpdw', label = _U('weapon_combatpdw') },
  WEAPON_MARKSMANPISTOL = {hash = `WEAPON_MARKSMANPISTOL`, item = 'weapon_marksmanpistol', label = _U('weapon_marksmanpistol') },
  WEAPON_KNUCKLE = {hash = `WEAPON_KNUCKLE`, item = 'weapon_knuckle', label = _U('weapon_knuckle') },
  WEAPON_HATCHET = {hash = `WEAPON_HATCHET`, item = 'weapon_hatchet', label = _U('weapon_hatchet') },
  WEAPON_RAILGUN = {hash = `WEAPON_RAILGUN`, item = 'weapon_railgun', label = _U('weapon_railgun') },
  WEAPON_MACHETE = {hash = `WEAPON_MACHETE`, item = 'weapon_machete', label = _U('weapon_machete') },
  WEAPON_MACHINEPISTOL = {hash = `WEAPON_MACHINEPISTOL`, item = 'weapon_machinepistol', label = _U('weapon_machinepistol') },
  WEAPON_SWITCHBLADE = {hash = `WEAPON_SWITCHBLADE`, item = 'weapon_switchblade', label = _U('weapon_switchblade') },
  WEAPON_REVOLVER = {hash = `WEAPON_REVOLVER`, item = 'weapon_revolver', label = _U('weapon_revolver') },
  WEAPON_DBSHOTGUN = {hash = `WEAPON_DBSHOTGUN`, item = 'weapon_dbshotgun', label = _U('weapon_dbshotgun') },
  WEAPON_COMPACTRIFLE = {hash = `WEAPON_COMPACTRIFLE`, item = 'weapon_compactrifle', label = _U('weapon_compactrifle') },
  WEAPON_AUTOSHOTGUN = {hash = `WEAPON_AUTOSHOTGUN`, item = 'weapon_autoshotgun', label = _U('weapon_autoshotgun') },
  WEAPON_BATTLEAXE = {hash = `WEAPON_BATTLEAXE`, item = 'weapon_battleaxe', label = _U('weapon_battleaxe') },
  WEAPON_COMPACTLAUNCHER = {hash = `WEAPON_COMPACTLAUNCHER`, item = 'weapon_compactlauncher', label = _U('weapon_compactlauncher') },
  WEAPON_MINISMG = {hash = `WEAPON_MINISMG`, item = 'weapon_minismg', label = _U('weapon_minismg') },
  WEAPON_PIPEBOMB = {hash = `WEAPON_PIPEBOMB`, item = 'weapon_pipebomb', label = _U('weapon_pipebomb') },
  WEAPON_POOLCUE = {hash = `WEAPON_POOLCUE`, item = 'weapon_poolcue', label = _U('weapon_poolcue') },
  WEAPON_WRENCH = {hash = `WEAPON_WRENCH`, item = 'weapon_wrench', label = _U('weapon_wrench') },
  WEAPON_FLASHLIGHT = {hash = `WEAPON_FLASHLIGHT`, item = 'weapon_flashlight', label = _U('weapon_flashlight') },
  GADGET_NIGHTVISION = {hash = `GADGET_NIGHTVISION`, item = 'gadget_nightvision', label = _U('gadget_nightvision') },
  GADGET_PARACHUTE = {hash = `GADGET_PARACHUTE`, item = 'parachute', label = _U('gadget_parachute') },
  WEAPON_FLARE = {hash = `WEAPON_FLARE`, item = 'weapon_flare', label = _U('weapon_flare') }, 
  WEAPON_SNSPISTOL_MK2 = {hash = `WEAPON_SNSPISTOL_MK2`, item = 'weapon_snspistol_mk2', label = _U('weapon_snspistol_mk2') }, 
  WEAPON_REVOLVER_MK2 = {hash = `WEAPON_REVOLVER_MK2`, item = 'weapon_revolver_mk2', label = _U('weapon_revolver_mk2') },  
  WEAPON_DOUBLEACTION = {hash = `WEAPON_DOUBLEACTION`, item = 'weapon_doubleaction', label = _U('weapon_doubleaction') },    
  WEAPON_SPECIALCARBINE_MK2 = {hash = `WEAPON_SPECIALCARBINE_MK2`, item = 'weapon_specialcarbine_mk2', label = _U('weapon_specialcarabine_mk2') },  
  WEAPON_BULLPUPRIFLE_MK2 = {hash = `WEAPON_BULLPUPRIFLE_MK2`, item = 'weapon_bullpuprifle_mk2', label = _U('weapon_bullpruprifle_mk2') },   
  WEAPON_PUMPSHOTGUN_MK2 = {hash = `WEAPON_PUMPSHOTGUN_MK2`, item = 'weapon_pumpshotgun_mk2', label = _U('weapon_pumpshotgun_mk2') },
  WEAPON_MARKSMANRIFLE_MK2 = {hash = `WEAPON_MARKSMANRIFLE_MK2`, item = 'weapon_marksmanrifle_mk2', label = _U('weapon_marksmanrifle_mk2') },  
  WEAPON_ASSAULTRIFLE_MK2 = {hash = `WEAPON_ASSAULTRIFLE_MK2`, item = 'weapon_assaultrifle_mk2', label = _U('weapon_assaultrifle_mk2') },
  WEAPON_CARBINERIFLE_MK2 = {hash = `WEAPON_CARBINERIFLE_MK2`, item = 'weapon_carbinerifle_mk2', label = _U('weapon_carbinerifle_mk2') },  
  WEAPON_COMBATMG_MK2 = {hash = `WEAPON_COMBATMG_MK2`, item = 'weapon_combatmg_mk2', label = _U('weapon_combatmg_mk2') },   
  WEAPON_HEAVYSNIPER_MK2 = {hash = `WEAPON_HEAVYSNIPER_MK2`, item = 'weapon_heavysniper_mk2', label = _U('weapon_heavysniper_mk2') },   
  WEAPON_PISTOL_MK2 = {hash = `WEAPON_PISTOL_MK2`, item = 'weapon_pistol_mk2', label = _U('weapon_pistol_mk2') },   
  WEAPON_SMG_MK2 = {hash = `WEAPON_SMG_MK2`, item = 'weapon_smg_mk2', label = _U('weapon_smg_mk2') }
}

Config.AmmoTypes = {
  AMMO_PISTOL = {hash = `AMMO_PISTOL`, item = 'pistol_ammo' },
  AMMO_SMG = {hash = `AMMO_SMG`, item = 'smg_ammo' },
  AMMO_FIREWORK = {hash = `AMMO_FIREWORK`, item = 'weapon_firework' },
  AMMO_RIFLE = {hash = `AMMO_RIFLE`, item = 'rifle_ammo' },
  AMMO_MG = {hash = `AMMO_MG`, item = 'mg_ammo' },
  AMMO_SHOTGUN = {hash = `AMMO_SHOTGUN`, item = 'shotgun_ammo' },
  AMMO_STUNGUN = {hash = `AMMO_STUNGUN`, item = 'stungun_ammo' },
  AMMO_SNIPER = {hash = `AMMO_SNIPER`, item = 'sniper_ammo' },
  AMMO_SNIPER_REMOTE = {hash = `AMMO_SNIPER_REMOTE`, item = 'sniper_remote_ammo' },
  AMMO_MINIGUN = {hash = `AMMO_MINIGUN`, item = 'minigun_ammo' },
  AMMO_GRENADELAUNCHER = {hash = `AMMO_GRENADELAUNCHER`, item = 'grenadelauncher_ammo' },
  AMMO_GRENADELAUNCHER_SMOKE = {hash = `AMMO_GRENADELAUNCHER_SMOKE`, item = 'grenadelauncher_smoke_ammo' },
  AMMO_RPG = {hash = `AMMO_RPG`, item = 'rpg_ammo' },
  AMMO_STINGER = {hash = `AMMO_STINGER`, item = 'stinger_ammo' },
  AMMO_BALL = {hash = `AMMO_BALL`, item = 'weapon_ball' },
  AMMO_STICKYBOMB = {hash = `AMMO_STICKYBOMB`, item = 'weapon_stickybomb' },
  AMMO_SMOKEGRENADE = {hash = `AMMO_SMOKEGRENADE`, item = 'weapon_smokegrenade' },
  AMMO_BZGAS = { hash = `AMMO_BZGAS`, item = 'weapon_bzgas' },
  AMMO_FLARE = {hash = `AMMO_FLARE`, item = 'weapon_flare' },
  AMMO_MOLOTOV = {hash = `AMMO_MOLOTOV`, item = 'weapon_molotov' },
  AMMO_TANK = {hash = `AMMO_TANK`, item = 'tank_ammo' },
  AMMO_SPACE_ROCKET = {hash = `AMMO_SPACE_ROCKET`, item = 'space_rocket_ammo' },
  AMMO_PLANE_ROCKET = {hash = `AMMO_PLANE_ROCKET`, item = 'plane_rocket_ammo' },
  AMMO_PLAYER_LASER = {hash = `AMMO_PLAYER_LASER`, item = 'player_laser_ammo' },
  AMMO_ENEMY_LASER = {hash = `AMMO_ENEMY_LASER`, item = 'enemy_laser_ammo' },
  AMMO_BIRD_CRAP = {hash = `AMMO_BIRD_CRAP`, item = 'bird_crap_ammo' },
  AMMO_PETROLCAN  = {hash = `AMMO_PETROLCAN`, item = 'weapon_petrolcan' }
  
}